### ISSUE TITLE
Bug in Advanced search options

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#100]
An FPANer reported a bug concerning the Advanced search in Arches. It looks like this bug is occuring in all accounts except the admin account where certain search options in the advanced search tab are not rendering properly. The bars for typing text and bringing up dropdown menu options are missing from the pages. This is affecting archaeological sites, historic cemeteries, and historical structures. This is occurring in the "Survey Evaluation", "Who Owns the site?", "Coordinates", "SHPO Evaluation", "Detailed Description", and "Located In" tabs. For Scout Report, there is an issue with the "Step 2", "Step 3", "Step 4", and "Step 6" tab search options. 

![image](https://user-images.githubusercontent.com/54329725/72939684-58c6a680-3d3b-11ea-9108-436be5adb384.png)

![60141455793__F1704EA1-B12B-429C-8147-A2C0EB2343FA](https://user-images.githubusercontent.com/54329725/72939984-fb7f2500-3d3b-11ea-80d3-6e1cbb38f34a.jpeg)
![60141420044__A237A028-225B-4C8A-9A15-2408C512B6F6](https://user-images.githubusercontent.com/54329725/72939985-fb7f2500-3d3b-11ea-8c95-e669ebc4e276.jpeg)

**Comment by mradamcox** [comment]
@coherit Would you be able to have a look at this ticket? I'm guessing it's somewhat of a backend fix, but it would be best if you have a look at it first. First thing is to see if it's reproducible on the staging server.

**Comment by coherit** [comment]
@mradamcox sure thing -- traveling back from Jamaica !Arches Training!) tomorrow so will put on my to do list for my return.

**Comment by coherit** [comment]
@kkemp85 Can you please confirm this is still happening on the staging site? I wasn't able to reproduce this as an anonymous user, a scout, land manager, or admin. I tested Chrome and Firefox. If this is still a problem, can you tell me what web browser and specific user account(s) is being affected? I'm hoping it was a CSS error that was fixed since January but could be a deeper permissions issue I haven't hit upon yet. Thanks!

**Comment by kkemp85** [comment]
@coherit I just checked all accounts and it doesn't look like this issue is occurring anymore. I will close the ticket, thanks!
