### ISSUE TITLE
Glitch with Land Manager group/new groups

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#101]
After logging into a new WMD account I created, I noticed a glitch with the main map page. I figured out that I could fix the glitch by adding an active group like StatePark, FL_Forestry, or FWC. So maybe something either needs to be done with the Land Manager group or we need to activate the FL_WMD group I made (along with that same vein the NPS group I made would need to be fixed too to avoid this issue once I start creating NPS accounts).

![image](https://user-images.githubusercontent.com/54329725/73089557-824f1180-3ea4-11ea-8502-41a375ae1a23.png)

**Comment by mradamcox** [comment]
@kkemp85 can you confirm this is still an issue? I think it should be handled now.

**Comment by kkemp85** [comment]
@mradamcox I just checked all the accounts and it's still glitching with the red bar at the top unfortunately

**Comment by kkemp85** [comment]
@mradamcox So looks like this glitch is now happening in all state park accounts as well. I was checking one of the State Park District accounts and noticed it. I checked a few of the other state park accounts and they are having the same issue. Must be something with the State Park group? This might be a big issue since we have active state park accounts.

![image](https://user-images.githubusercontent.com/54329725/76031921-bc312000-5f06-11ea-8391-09f48c79f329.png)

**Comment by mradamcox** [comment]
@kkemp85  Ok I just looked into this and figured it out, it was related to the new water management district configuration. I'm now able to login as a state park account and see the search page without error.

**Comment by kkemp85** [comment]
@mradamcox great! Looks like it's fixed on the WMD accounts as well. I'll close the issue.

**Comment by kkemp85** [comment]
@mradamcox This issue is fixed on all the WMD accounts except the admin one: SJRWMD_Admin. I am pretty positive I checked it with the others when we closed this issue and it was working properly but is not now, unfortunately.

**Comment by mradamcox** [comment]
@kkemp85 Ok, I'll look into it. Shouldn't be too hard to track down now.

**Comment by mradamcox** [comment]
@kkemp85 This account should now work correctly, can you confirm?

**Comment by kkemp85** [comment]
@mradamcox yes it is fixed! Thank you!
