### ISSUE TITLE
Improve new resource screen with more HMS specific info

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#103]
This seems like a perfect place to put in more instructions for people that are about to make a new Scout Report
![image](https://user-images.githubusercontent.com/10427268/73093798-e40f7b80-3ea4-11ea-950e-984de49825fe.png)
@kkemp85 can you work on figuring out what information would be the most helpful?

**Comment by kkemp85** [comment]
@mradamcox  yes I can definitely do that! We've been hoping to have a place to put general instructions about how to log a report and this seems like the perfect place. I'll get to work on something.

**Comment by kkemp85** [comment]
@coherit Here is what I came up with. Feel free to play with the spacing and such to make it flow better on the page, I wasn't sure how I wanted the sentences broken up. It would be great if we could get an image of the Help icon ![image](https://user-images.githubusercontent.com/54329725/73573272-f8bdb780-4440-11ea-88cb-14fc719067b2.png) to show up in the last sentence. 



Welcome to the HMS Florida Scout Report System!

You are about to create a new Scout Report record or, as it is known in the Arches Database, a “New Resource”. The tree structure on the left lists all six pages of the Scout Report you will log. You will click on each page to fill in the required information. Information marked with an *asterisk is required. Please click “Add” after you have completed each page and you will see your new entry show up in the tree on the left. **Clicking “Add” will only save the page you are currently editing, not the entire report, so you must click “Add” at the end of every page to save.**

Steps 1 through 4 are required. If you are logging a report for an Archaeological Site or Historic Cemetery, you may skip Step 5. If you do not have photos from your monitoring visit, skip Step 6.

Have questions about a specific page? Click the ![image](https://user-images.githubusercontent.com/54329725/73573306-0a06c400-4441-11ea-8519-78cbd71c6b2f.png) feature at the top right of each page for more details and helpful information about each step and its questions.

**Comment by coherit** [comment]
@kkemp85 I've now edited this for the Scout report. Do you want to replace the default text for other resource types like cemeteries, sites, or structures? Right now, I have it just showing the default Arches text for those resource reports. 

![image](https://user-images.githubusercontent.com/3217017/75069240-cb53af00-54be-11ea-8dbb-9d88a320f7ae.png)

**Comment by mradamcox** [comment]
@coherit I'm not seeing this commit anywhere. What branch do you have it on? I'm going to consolidate all of our branches, so if you haven't pushed it yet, the best plan will be for you to pull the `master` branch, create a new branch from it, cherry-pick this commit into your new branch, then push the new branch here. We'll do a pull request then.

**Comment by coherit** [comment]
@mradamcox I haven't committed this yet because I was waiting for feedback on the other reports. I'll keep the other reports as the default and follow your git instructions.

**Comment by mradamcox** [comment]
Ok, that makes perfect sense. I know @kkemp85 has been out of the office but will be back in a few days.

**Comment by coherit** [comment]
@mradamcox pushed this as a new branch 103_improve_new_resource_screen

**Comment by kkemp85** [comment]
@coherit This looks so great, thank you! As for the other resources, only admin accounts can see these resource screens and add sites, cemeteries, and structures so there's not really any reason to alter the text for those.

**Comment by mradamcox** [comment]
@coherit it looks like that new branch somehow has the old commit about adding underscores to the file download name: https://github.com/legiongis/fpan/commits/103_improve_new_resource_screen. Could you make a new branch from master and then cherry-pick the improved resource screen commit to it? That should clear this up.

**Comment by mradamcox** [comment]
Ok, looks great now. Thanks!
