### ISSUE TITLE
Add Historic Map Overlay to Package Load

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#104]
Look in the load_package command.

**Comment by coherit** [comment]
@mradamcox Okay -- I've worked on this and wanted to test it. However, when I re-run your special load package command (python manage.py load_package -db), I'm getting an error (below). (Same thing when I roll back my changes to the load package command).

What is the correct way to reload the package data? End of the day so I could be missing something stupid...

  

> Traceback (most recent call last):
>   File "manage.py", line 29, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
>     utility.execute()
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
>     self.check()
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
>     include_deployment_checks=include_deployment_checks,
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
>     return checks.run_checks(**kwargs)
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
>     new_errors = check(app_configs=app_configs)
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
>     return check_resolver(resolver)
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
>     return check_method()
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
>     for pattern in self.url_patterns:
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
>     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
>     return import_module(self.urlconf_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/home/alabra/fpan/fpan/urls.py", line 4, in <module>
>     from .views import main, report, auth, scout, search
>   File "/home/alabra/fpan/fpan/views/main.py", line 10, in <module>
>     from fpan.utils.permission_backend import user_is_anonymous, check_state_access
>   File "/home/alabra/fpan/fpan/utils/permission_backend.py", line 7, in <module>
>     settings.update_from_db()
>   File "/home/alabra/arches/arches/app/models/system_settings.py", line 79, in update_from_db
>     for node in models.Node.objects.filter(graph_id=self.SYSTEM_SETTINGS_RESOURCE_MODEL_ID):
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
>     self._fetch_all()
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
>     self._result_cache = list(self._iterable_class(self))
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
>     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
>   File "/home/alabra/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
>     raise original_exception
> django.db.utils.ProgrammingError: relation "nodes" does not exist
> LINE 1: ...", "nodes"."isrequired", "nodes"."sortorder" FROM "nodes" WH...

**Comment by mradamcox** [comment]
@coherit I recently encountered some serious issues in reloading the package too. Not the same error, but potentially related. I added a new page to our HMS Notion (named "Setup DB Issues 3/1/20") which describes a workaround. Please let me know if that works for you.

**Comment by coherit** [comment]
@mradamcox Unfortunately the workaround doesn't help and is currently foobared. However, I think the/my issue may be related to the fpan/utils/permission_backend.py file, which, when I was committing issue 76 in those bad pull requests, there were two lines related to those functions. 

https://github.com/legiongis/fpan/pull/108/commits/a9d7ac5e9b606448e7d806fc7d18da98143a476b

Do you think that there were some changes dropped somewhere? Or new changes introduced and merged that are breaking things?

**Comment by coherit** [comment]
@mradamcox  can confirm that commenting out line 7 of utils/permission_backend.py fixed the load_package command.

`#settings.update_from_db()`

**Comment by mradamcox** [comment]
Great, and did you get a "database connection terminated" error, or did it proceed as normal? Maybe that error I got just has to do with my local postgres installation.

**Comment by coherit** [comment]
No -- it completed successfully all the way through.

**Comment by coherit** [comment]
FYI -- when running the load_package function, I do get a lot of these warnings as it loads resources: badly formed hexadecimal UUID string invalid nodegroupid participating in descriptor function.

**Comment by coherit** [comment]
@mradamcox This is ready for review in branch 104_add_maplayers. You can run just this component with:
`python manage.py load_package -c maps --exclude_business_data`

It should load both tileserver and mapbox layers (as long as the directory structure for the package is correct):

- fpan-data
  - map_layers
    - mapbox_spec_json
      - basemaps
        - [dir with contents]
      - overlays
        - [dir with contents]
    - tile_server
      - basemaps
        - *.json or *.xml
      - overlays
        - *.json or *.xml

**Comment by mradamcox** [comment]
All good in testing. Thanks!
