### ISSUE TITLE
Create St Johns River WMD accounts, FL_WMD group, and WMD management areas

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#105]
@mradamcox and I have been working through email to set up these new accounts and to create a plan of action for Water Management District (WMD) accounts in general. Logging here for coherence.

**Comment by mradamcox** [comment]
Ok, this is all ready to go. You'll need to set the archaeological site attributes that drive the permissions manually. Make sure all sites have the Managed Area Category set to Water Management District, this will enable the SJRWMD account to see all of them.

For more specific access, you need to set the Managed Area Name for each site. Then all of the other WMD users will see the sites that are either in their district or in their region.

**Comment by kkemp85** [comment]
@mradamcox I added all the Managed Area names to the RDM and have started tagging sites. They are showing up in the search bar immediately which is great! But the site polygons aren't showing up in the map just like the issue we are still having with the State Park District accounts.

**Comment by mradamcox** [comment]
@kkemp85 I have fixed the issue with both the State Park District accounts and the WMD accounts. There was an issue with how the query was constructed for multiple terms, which is how these aggregate access levels work. All good now. I'm not sure there was really a separate ticket for the SP District issue, but could you look through and close if so? Thanks :)

**Comment by kkemp85** [comment]
@mradamcox yes these are all working great now thank you!
