### ISSUE TITLE
Create Arches 5-compatible File to Load 1919 Coastal Map

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#117]
In Arches 4 we were using the built-in Arches tileserver (tilestache) to cascade the WMS from Geoserver that provides the 1919 Coastal Map. Arches 5 has done away with the tileserver, so we need to create a different load file for that map. I believe there are examples of using Geoserver WMS layers in other v5 installations, and I also think there has been some talk of it on the forum (perhaps the developer forum).

**Comment by coherit** [comment]
Notes from discussion on this -- could require settings changes on geoserver because of CORS issues

**Comment by mradamcox** [comment]
Recent forum post about this: https://groups.google.com/forum/#!topic/archesproject/vaBMwbYp6IY

**Comment by mradamcox** [comment]
New map source and layer are now in stored in a json fixture that is loaded with a migration.
