### ISSUE TITLE
Replicate Issue 79, User ID should be autopopulated for Arches 5

### ISSUE THREAD

**Issue by coherit** [legiongis/hmsf-md#122]
See the original issue https://github.com/legiongis/fpan/issues/79

**Comment by coherit** [comment]
@mradamcox this is now applied in branch  122_scoutid_auto_upgradeto5.

I expect to have to return to this with the collector, but will address those changes under a different branch.

**Comment by mradamcox** [comment]
Looks good! When it comes to the collector, I'm not sure how this will work because I don't think these custom templates are passed along with a mobile collection project. In fact, I have no idea whether custom widgets of any sort are supported in the mobile app.
