### ISSUE TITLE
Fix scrolling on adding new resource

### ISSUE THREAD

**Issue by coherit** [legiongis/hmsf-md#125]
The content area when adding a new resource (and perhaps other places) do not show scrollbars when they should. 

.content-panel {
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column;
    width: 100%;
    height: calc(100vh - 50px); ***TOGGLING THIS HELPS ***
    position: relative;
}

**Comment by coherit** [comment]
also check for issues from media/index.css

**Comment by coherit** [comment]
@mradamcox  Fixed in branch 125_cssfixes:

- scroll bar on map for 1 px (this was a "feature" -- resized heights to fix)
- no scroll bar when adding resources (overflow defaulting to hidden - scroll bar now appears)
- illegible fonts on cards (updated interior admin headings to same ratio as exterior, 16px base)
- strangely centered icons in upper left (removed border around icons to fool eye)
- missing ionicons on login pages (added missing css call to packages/ionicons)

**Comment by mradamcox** [comment]
@kkemp85 This is now deployed, you may have to hard refresh your browser and advise others to do the same.
