### ISSUE TITLE
Creating State Park group accounts

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#127]
The State Park managers would like us to add an additional account level between the individual park unit account (like Tomoka State Park) and the District level accounts. These new group or cluster accounts will be able to see sites from two or more parks that are under the same park manager. That way, a park manager who manages 5 parks will not need to login to 5 different accounts to see monitoring progress over his managed lands. An example is the Talbot Island GEOpark, a collection of 7 different state parks all managed by one individual. While each park will retain its individual account (BigTalbotIslandSP, AmeilaIslandSP, etc.) we will create a new account called TalbotIslandGEOpark that will have access to all 7. I can create the accounts in Django and will send an excel of these clusters once we get the information from State Park staff.

**Comment by mradamcox** [comment]
This is now possible with the new Land Manager account system.
