### ISSUE TITLE
Update template's copyright info

### ISSUE THREAD

**Issue by coherit** [legiongis/hmsf-md#129]
Should read copyright 2020 and Arches 5.

**Comment by neilsilberman** [comment]
@mradamcox could you please add me as a collaborator on the FPAN repo?

**Comment by mradamcox** [comment]
done

**Comment by neilsilberman** [comment]
@mradamcox fixed in branch 129_copyright (used Django template tag to insert current year for copyright to make it dynamic).

**Comment by neilsilberman** [comment]
@mradamcox now corrected

**Comment by mradamcox** [comment]
Looks good, thanks!
