### ISSUE TITLE
New Arches 5 site info pop-up box- change site info read-out

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#132]
I love the new feature in Arches 5 where the pop-up box hovers over the site when you click on it, instead of the box set static at the top left of the map but, with this new feature, the site numbers are getting cut off. A lot of site names are really long and while seeing the whole site name is important, seeing the site number is more important. Is there a way to set that field to be longer or to wrap the text so that the whole thing is visible? Clicking to open the report to view the site number sort of defeats the purpose of this really helpful feature. See examples in the photo below.

![image](https://user-images.githubusercontent.com/54329725/78079355-ed700500-7379-11ea-83bc-efdc2a7d8801.png)

![image](https://user-images.githubusercontent.com/54329725/78079414-0f698780-737a-11ea-9ee2-c0ca2aed19b1.png)

**Comment by mradamcox** [comment]
@kkemp85 One easy way to address potentially address this would be to change the display name to "(Siteid) Site Name" from the current "Site Name (Siteid)". This would change all across the site though. Does that sound ok?

**Comment by kkemp85** [comment]
@mradamcox yes absolutely! We almost always identify sites by Site ID only, so seeing that is much more important than the site name. Plus, when we export, if the Site ID is first it is more beneficial to us to sort by Site ID, and therefore county, then it is by site name.

**Comment by mradamcox** [comment]
Sounds good. Next week during our meeting I'll show you how to do this within the interface. Reindexing will take a few hours, so it will be best for you to do it at night.

**Comment by mradamcox** [comment]
All done, and the resource models with changed functions have been exported and committed to the fpan-data repo.
