### ISSUE TITLE
Load new Mapbox overlays into staging server, add as layers in package

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#139]
These are two new Mapbox layers that @kkemp85 has made, which should get loaded into the staging server.

FPAN Regions
mapbox://styles/hmsflorida/ck8yzb8oo02el1jp6favnyhlc

State Park Districts
mapbox://styles/hmsflorida/ck8oy1eci04tc1in56ymfubxh

These layers should be added as overlays.

**Comment by coherit** [comment]
@mradamcox  Can I get the credentials for the hmsflorida mapbox account or a "share style" link for these styles? Thanks!

**Comment by kkemp85** [comment]
@coherit I thought those were the share links but I must've made a mistake! I don't mind sharing the HMSflorida Mapbox login account information with you, but don't want to do so over Github. I will send to you through email.

**Comment by coherit** [comment]
@kkemp85 No worries!! I did too until they didn't work  :-) I think the share links start with http://api.mapbox... and you have to make them public: [directions](https://docs.mapbox.com/help/troubleshooting/transfer-styles-between-accounts/)

**Comment by kkemp85** [comment]
@coherit Oh, I see. Yeah, I did not make them public!

**Comment by coherit** [comment]
Working in dev -- @mradamcox can I have contributor access to the https://github.com/legiongis/fpan-data repo? Thanks!

**Comment by coherit** [comment]
The overlays are now loaded in the staging server. However, this uncovered a css issue I need to fix (fixing the weird 1px scroll on the search/ page broke scrolling on the map settings page). I'll tackle that tomorrow.

**Comment by coherit** [comment]
This is now completed and up on staging for review. Had to change the mapbox api key on staging to use the hms account -- you may need to do the same on production to get the overlays to appear. 

Additional mapbox layers must be loaded in their own directory in the package file:

- fpan-data
-- map_layers
--- mapbox_spec_json
--- basemaps
---- [name of basemap]
----- *.json
--- overlays
---- [name of overlay]
----- *.json

Command to load additional mapbox layers:
`python manage.py load_package --exclude_business_data -c maps
`

Also removed tileserver load functions and tweaked an overflow css tag that was preventing scrolling in the map settings area.

**Comment by kkemp85** [comment]
@coherit these look really good!

**Comment by coherit** [comment]
@kkemp85 Thanks -- you made them! ;-) Great work on the mapbox side!!

**Comment by kkemp85** [comment]
@coherit thanks! Mapbox is fun!

**Comment by mradamcox** [comment]
@kkemp85 These are now loaded into production. They look great :) @coherit I did update the mapbox key to make it work, good to get that taken care of anyway.
