### ISSUE TITLE
Fix region descriptions on Scout Profile page

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#141]
The region listings on the Scout Profile page are showing up as generalized "Region objects" instead of the correct region names. This is making it difficult for new scouts to complete account information.

![image](https://user-images.githubusercontent.com/54329725/80527938-26909a80-8963-11ea-99a4-cd0b1a017dfc.png)

**Comment by mradamcox** [comment]
Just deployed this fix, a lingering python 2 to 3 upgrade issue.
