### ISSUE TITLE
Update text in auto-generated email to scouts upon initial sign-up

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#143]
@mradamcox and I discussed this a while back and this is an issue related to issue #93. We would like to update the verbiage for the email that is auto-sent to new scouts upon initial sign-up to Arches. We would like it to be more explicit that sign-up is a two-step process, at least until we can figure out a way to streamline and combine these steps. We would like the email that is sent to read as follows:

**Hello [Scout ID]!**
Welcome to the Heritage Monitoring Scouts, we're excited to have you! To grant you access to the database and connect you with resources in your area, we need to learn a bit more about you. Please follow the instructions below to complete your registration. 
 
To Activate Your Account:
 
1.	Click [this link] to verify your email. 
 
2.	The link above will take you to the Scout Login page. Use your scout ID (specific Scout ID here) and password to log in. Once you are logged in, scroll down to fill in the rest of your Scout Profile. Your account is not active until you fill in this information. 
 
*If the above link is broken or expired, simply go to the "Scout Portal" located [here](https://hms.fpan.us/auth/hms) and log in to your account there to complete your profile. You will be able to access the database from this portal for all future visits.

**Thanks for Signing Up and Welcome Aboard!**

**Comment by coherit** [comment]
This has now been committed in branch https://github.com/legiongis/fpan/tree/143_email_template. I don't have SMTP on my dev box to test full workflow.
