### ISSUE TITLE
Update text on Land Manager landing page

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#144]
The simple sentence on each Land manager page is no longer accurate and I would like to update it. It will vary for each type of land manager account as follows:

As a Forest Service user, you have access to all Archaeological Sites within the State Forest(s) you manage.

As a State Park user, you have access to all Archaeological Sites within the State Park(s) you manage. 

As a Fish and Wildlife Commission user, you have access to all Archaeological Sites within the WMA/WEA(s) you manage.

As a Water Management District user, you have access to all Archaeological Sites within the Conservation Area(s) you manage.  

 
![image](https://user-images.githubusercontent.com/54329725/81857729-a9ebe780-9530-11ea-963f-13d07afa5eee.png)

**Comment by coherit** [comment]
Edited and committed to new branch (had to add the FL_WMD if statement, assuming that's the water management user group):
https://github.com/legiongis/fpan/compare/144_lms_usergroup_text

**Comment by coherit** [comment]
Revisiting this -- the statements I have now are below -- @kkemp85 let me know if these look good or if others should be changed as well:
```
{% if request.user.is_superuser %}
     <p>{% trans "As an admin, you have <strong>full access</strong> to the database." %}</p>
 {% elif request.user|has_group:"StatePark" %}
      <p>{% trans "As a State Park user, you have access to all Archaeological Sites within the State Park(s) you manage.." %}</p>
{% elif request.user|has_group:"FWC" %}
      <p>{% trans "As a Fish and Wildlife Commission user, you have access to all Archaeological Sites within the WMA/WEA(s) you manage." %}</p>
{% elif request.user|has_group:"FL_BAR" %}
       <p>{% trans "As the Florida Bureau of Archaeological Research you have access to <strong>all</strong> Archaeological Sites." %}</p>
{% elif request.user|has_group:"FMSF" %}
       <p>{% trans "As a Florida Master Site File user you have access to <strong>all</strong> Archaeological Sites." %}</p>
{% elif request.user|has_group:"FL_Forestry" %}
        <p>{% trans "As a Forest Service user, you have access to all Archaeological Sites within the State Forest(s) you manage." %}</p>
{% elif request.user|has_group:"FL_AquaticPreserve" %}
       <p>{% trans "As a Florida Aquatic Preserve user you have access to <strong>all</strong> Archaeological Sites on any Aquatic Preserves." %}</p>
{% elif request.user|has_group:"FL_WMD" %}
       <p>{% trans "As a Water Management District user, you have access to all Archaeological Sites within the Conservation Area(s) you manage." %}</p>
{% endif %}
```

**Comment by kkemp85** [comment]
@coherit yes these look great!

**Comment by mradamcox** [comment]
ok deploying this now. This will actually change again quite soon with the new Land Manager profiles, but glad to have this fix in in the meantime.
