### ISSUE TITLE
Put text from #144 into site-filter panel on search page

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#146]
Connected to #144, the same text that is to be displayed in the state home page should be put into the "site-filter" panel that is available in the main search page.
![image](https://user-images.githubusercontent.com/10427268/82070091-dc652400-9699-11ea-9d20-a82b891ef59b.png)
Some basic styling should be added to the panel as well.

**Comment by coherit** [comment]
@mradamcox possibly stupid question -- but how do I turn on the search filter with the key?
![image](https://user-images.githubusercontent.com/3217017/129387243-2706c364-2dbb-4af1-959e-7a3b890c8d76.png)

**Comment by mradamcox** [comment]
You can register that search component with `python manage.py search
register -s fpan/search/components/site-filter.py`.

I'm working a lot on the land manager and scout profiles right now, so this
text will be autogenerated soon directly from a users profile. Will have
more on that next week.

**Comment by coherit** [comment]
ok, i will will hold off then until that's done!

**Comment by mradamcox** [comment]
Completed.
