### ISSUE TITLE
Remove Resource ID from the Map Pop-up on all resources

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#148]
I would like to remove the Resource ID number from the Map pop-up for all three resources on our map. I think it's distracting especially since this number is just for us and doesn't really mean anything to our users. Will make the pop-up look much cleaner! I do want to keep the Resource Model section however.

![image](https://user-images.githubusercontent.com/54329725/82691489-fff51500-9c2b-11ea-9441-64635848100c.png)

**Comment by coherit** [comment]
Now overriding the map popup component in the search page to omit the resource id. Committed in branch https://github.com/legiongis/fpan/tree/148_mappopup_omituuid

**Comment by kkemp85** [comment]
Just noticed this was complete. Looks good, thanks!
