### ISSUE TITLE
Make FPAN 404 and 500 templates

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#16]
we need some basic error templates in the root of the templates directory.

**Comment by mradamcox** [comment]
I think these templates should inherit from `base-manager.htm`, as opposed to `fpan-base.htm`. This is because I expect that the vast majority of 404 or 500 errors will occur within the database pages, not our small set of home/login pages.

**Comment by bedubs** [comment]
When I use `base-manager.htm`, I get a 500 (even on a 404) and a `VariableDoesNotExist` error. It's looking for a `nav` variable. When I use `base.htm`, which is what `base-manager.htm` extends, I get a never-ending time wheel. Do you know if there is a way to pass that `nav` variable to the 404 response? When I extend `fpan_base.htm`, I don't have a problem, but it doesn't use the right base template.

**Comment by mradamcox** [comment]
I see what you mean about the `nav` variable. Let's use the `fpan_base.htm` template for these 500 and 404 templates. I think that's the best way to solve it for now.

**Comment by mradamcox** [comment]
looks great, though I found this arches issue in the meantime: https://github.com/archesproject/arches/issues/2888
