### ISSUE TITLE
Adding Zip Code to the Scout Sign up process

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#167]
@mradamcox and I have discussed before the issue we are having with the two-step signup process where Scouts sign up, then have to activate their account before they can go in and fill in their profile. We need the Scout profile info for tracking outreach and program extent data. We know there isn't an easy or quick fix to this issue for right now, but we thought one temporary solution might be to add the zip code as part of the first sign-up step and making it required. That way, we can track where our Scouts are signing up from, even if they never go back to complete their profiles. Hopefully, this is an easy task!

![image](https://user-images.githubusercontent.com/54329725/89676618-f76ebb00-d8b9-11ea-9988-d6085ea1cc5c.png)

**Comment by mradamcox** [comment]
Closing in favor of the larger overhaul in #93
