### ISSUE TITLE
New basemap for Arches

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#170]
I am creating a new basemap for Arches that will have county outlines embedded into the map, something we've desperately needed. Once the map is complete, I will send over to @mradamcox for upload to the system.

**Comment by mradamcox** [comment]
Added to fpan-data and deployed to prod server. looks good!
![image](https://user-images.githubusercontent.com/10427268/183768830-0eb66bc6-2f1e-49b0-80a6-8749fda103db.png)
