### ISSUE TITLE
Create Hillsborough County Arches accounts

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#173]
We have been working with more and more local land managers at the county and city level who are interested in using Arches as part of their management responsibility routine. Hillsborough County was looking to get accounts for all of its parks and preserve land. These accounts will be set up similar to State Park accounts, in the sense that the account will only be able to see arch sites within specific land parcel boundaries so we will need to integrate the shapefiles they provided us into the "Managed Area" section on Django. @mradamcox and I discussed using the Hillsborough County account set up as a guinea pig for the new system he plans to set up for all land manager accounts. This will streamline the process and make it easier for me to create land manager accounts.

**Comment by mradamcox** [comment]
This is now live in production. Improvements will still be made to speed up the performance of the geo filter that this account uses, but those updates will be handled in other tickets.
