### ISSUE TITLE
Connecting to Collector with Arches 5.1

### ISSUE THREAD

**Issue by coherit** [legiongis/hmsf-md#178]
This is a continuation of Issues #85 and #153 but for Arches 5.1.

**Comment by coherit** [comment]
After upgrading the staging server to Arches 5.1, I checked what version of couchdb was running:
`curl localhost:5984
`
which returned 3.1.1. (You can also look at the releases in /opt/couchdb.)

I then followed the docs we had on notion to replace with 2.3.1:

```
sudo apt-get --purge remove couchdb
sudo apt-cache policy couchdb
sudo apt-get install couchdb=2.3.1~bionic
```
[set admin password]

test to see if running:
`curl http://admin:[password]@127.0.0.1:5984
`

I activated a new collector project on fpan staging, and watched the apache error log, which returned:

```
[
Mon Jan 11 13:02:39.774668 2021] [wsgi:error] [pid 14766:tid 139878478206720] [remote 174.83.44.71:59270] Starting sync for userid 1
[Mon Jan 11 13:02:39.774919 2021] [wsgi:error] [pid 14766:tid 139878478206720] [remote 174.83.44.71:59270] Sync failed for userid 1, with error:
[Mon Jan 11 13:02:39.774998 2021] [wsgi:error] [pid 14766:tid 139878478206720] [remote 174.83.44.71:59270] Celery appears not to be running, you need to have celery running in order to sync from Arches Collector.
[Mon Jan 11 13:02:39.777429 2021] [wsgi:error] [pid 14766:tid 139878478206720] [remote 174.83.44.71:59270] Internal Server Error: /sync/649ea3ec-d1c0-40cc-b01e-9793d58707cd

```

I get this on both http and https. Going to look into whether celery is now required and to look back through the edits made in previous versions of Arches. The ones that fixed auth issues in #85 were merged, so I'm surprised I'm getting this error.

**Comment by coherit** [comment]
@mradamcox If Dennis and I were understanding each other in slack, it sounds like we're going to have to get celery up and running on staging. (Adding note here for myself to add issue to docs to clarify this requirement in 5.1 and to fix link in docs to celery brokers). 

Would you like me to get celery set up? Do you have a preference for broker?

**Comment by mradamcox** [comment]
@coherit yes, it would be great if you could get that started. Let's go with rabbitmq. After a little discussion about the new requirement, I've also updated the Arches docs: https://arches.readthedocs.io/en/stable/arches-collector-checklist/#configure-a-celery-broker

**Comment by coherit** [comment]
Installed RabbitMQ following instructions at 
https://docs.celeryproject.org/en/v4.4.4/getting-started/first-steps-with-celery.html
https://docs.celeryproject.org/en/v4.4.4/getting-started/brokers/rabbitmq.html  

Configured the broker using credentials in notion. Left the guest user intact, but you may want to remove guest user on production if you have security concerns.

Edited settings_local.py to add CELERY_BROKER_URL and CELERY_RESULT_BACKEND as listed here https://arches.readthedocs.io/en/stable/task-management/?highlight=celery#configuration

Running 
`python manage.py celery start
`
results in:
```
 Error:
Unable to load celery application.
The module fpan_stage_new was not found.
```
Which seems to be the most generic celery error. I am wondering if it's a permissions issue but am not sure. 

I did install supervisor and copied its conf files over to /etc/supervisor. It starts successfully, but then fails when spawning celery. 
2021-01-12 19:08:55,325 INFO daemonizing the supervisord process
2021-01-12 19:08:55,326 INFO supervisord started with pid 1843
2021-01-12 19:08:56,328 INFO spawned: 'celery' with pid 1844
2021-01-12 19:08:57,599 INFO exited: celery (exit status 1; not expected)
2021-01-12 19:08:58,602 INFO spawned: 'celery' with pid 1847
2021-01-12 19:08:59,870 INFO exited: celery (exit status 1; not expected)
2021-01-12 19:09:01,878 INFO spawned: 'celery' with pid 1852
2021-01-12 19:09:03,217 INFO exited: celery (exit status 1; not expected)

**Comment by coherit** [comment]
Replacing settings.ELASTICSEARCH_PREFIX with arches in the celery.py management command starts celery successfully. The Collector App successfully connects over https and I'm able to add a scout report, however I get a celery error on the sync of the report. 

`[2021-01-14 16:35:19,474: WARNING/ForkPoolWorker-1] Sync failed for userid 1, with error:
string indices must be integers
  File "/opt/stage/arches/arches/app/models/mobile_survey.py", line 322, in _sync
    self.push_edits_to_db(synclog, userid)
  File "/opt/stage/arches/arches/app/models/mobile_survey.py", line 407, in push_edits_to_db
    tile.save(user=sync_user)
  File "/opt/stage/arches/arches/app/models/tile.py", line 359, in save
    datatype.pre_tile_save(self, nodeid)
  File "/opt/stage/arches/arches/app/datatypes/datatypes.py", line 1750, in pre_tile_save
    "resourceinstanceidto_id": related_resource["resourceId"],
`

Need to follow up on this error and correct the configuration so we're not overriding the celery.py file (if we don't have to). I posted to the arches forum https://groups.google.com/g/archesproject/c/0HLd9nHSJU8

**Comment by coherit** [comment]
Alexei pointed out on the forums that we were missing a celery.py file in our project folder. I copied that in from the project template in the arches folder, but still hit the same error, as @mradamcox predicted. Editing the arches management command to say "fpan" instead of the settings.ELASTICSEARCH_PREFIX variable worked though. Will write back to the forum and see if this is a bug.

**Comment by mradamcox** [comment]
Due to the impending deprecation of the Arches Collector app, we won't be pursuing this support anymore.
