### ISSUE TITLE
Public map issue

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#180]
The HMS website allows visitors without logins to view the HMS Arches map with structures and cemeteries. It removes archaeological sites because there are protections on their locations. However, I just noticed that Scout Reports for archaeological sites are accessible, visible, and printable. Many of these Scout Reports have information on archaeological site locations, especially if the photos were taken with the Solocator app, which put coordinates on the photos. This is a huge problem. 

We need to remove access to these reports on this public map. It would be ideal if we could just hide the archaeological site Scout Reports from this map but I understand this is easier said than done.  If it isn't quick or easy to just remove the archaeological Scout Reports from this map can we remove/hide ALL Scout Reports from this map??

This sort of goes along with our issue of scouts only being able to see Scout Reports for sites they have access to (Issue #152)  but is different since this is a public map anyone can access without a login account.

**Comment by mradamcox** [comment]
This is now fixed and deployed to production: public users cannot see any scout reports. When #152 is addressed we'll look at how to allow access to reports that are connected to structures or cemeteries.
