### ISSUE TITLE
Time Filter Calendar misplaced

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#183]
This may be an issue with all Arches instances with the upgrade to Arches 5.1, but the calendar for the "To" date selection now pops up in the middle of the map frame when you click on it instead of below the "To" field as it should. 

![image](https://user-images.githubusercontent.com/54329725/106930394-7ca92000-66e3-11eb-8c30-4518056ac7de.png)

**Comment by coherit** [comment]
Confirming this is still an open issue for Arches 5.2.x and I didn't find an open issue for this particular bug. Will work on a fix to contribute.

**Comment by coherit** [comment]
@mradamcox This is a very easy one line css fix. Basically, if the container that the input field is not position:relative, then this positioning bug occurs (known "feature" of the bootstrap datetimepicker). Fix can be applied to arches.css (tag is .calendar.picker). 

Do you want me to make this fix on the legiongis/arches/5.1.fpan branch? Make a new branch? Or fix this in the fpan repo in the project's css file and then contribute the fix to the community separately?

**Comment by mradamcox** [comment]
I'd say the last option is preferable. It would be best to make ticket in the Arches repo referencing this one and then make a pull request to the master arches branch.

**Comment by coherit** [comment]
@mradamcox Just upgraded another dev box with arches 5.2. I apt-get installed python3-dev to head off the error with rjsmin. Also upgraded node as per the ubuntu setup script. Upgraded arches homepage loads with 5.2 beta -- but when I go to /search I get a template error with compress (below). Do I need to change anything with settings.py? Did you encounter this with your 5.2 demos? (I would have just branched off of 5.1.4, but the calendar widget error wasn't there -- but it is in your 5.2 demos...).

```
TemplateSyntaxError at /search
'compress' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
guardian_tags
i18n
l10n
log
static
staticfiles
template_tags
tz
```

**Comment by mradamcox** [comment]
Yeah, I think you'll just need to add the "compressor" app to
INSTALLED_APPS. I haven't updated this project yet to work with Arches 5.2,
but if you are able to get this working that would be great. Here's more
about the compressor upgrade:
https://github.com/archesproject/arches/pull/7396.

**Comment by mradamcox** [comment]
Merged into master branch, closing ticket now. Thanks @coherit.
