### ISSUE TITLE
Issue with sites assigned to Scouts

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#188]
We are having an issue with sites assigned to scouts. It seems that after they are assigned, the scout can see the site in the Results Pane just fine, but when you click on the resource to open the report page, it gives an “Error 404” message instead of opening the report. Also, if you try to zoom in on the site in the map, the polygon is not showing up either, just the black marker to show that it’s a resource currently shown in the Results Pane.

This seems to be a recent issue as reports for sites that have been assigned to scouts for long periods of time seem to open just fine.

**Comment by mradamcox** [comment]
@kkemp85 this is the issue that has arisen a few times but I was able to fix, correct? It was fixed those times by manually refreshing the permissions table.

**Comment by kkemp85** [comment]
@mradamcox yes that is correct. I will close this ticket
