### ISSUE TITLE
Improve conditional CSS loading based on user type

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#198]
Currently we have a template `if` statement used to conditionally load different css stylesheets based on who is viewing the page, e.g. https://github.com/legiongis/fpan/blob/master/fpan/templates/fpan_base.htm#L66. This is slow and not a good solution.

To improve this conditional loading, all css classes should be combined in a single file and then renamed to include the `{{ user_type }}` string https://github.com/legiongis/fpan/blob/master/fpan/utils/context_processors.py#L54. For example, class `hover`  in the html should be `hover-{{ user_type }}`, and new variable classes should replace `.hover` (https://github.com/legiongis/fpan/blob/master/fpan/media/css/hms-style.css#L44).

Open to other ideas, but hopefully this makes sense.

**Comment by coherit** [comment]
@mradamcox  I'm working on this now and have predictable behavior when the user is anonymous, scout, or landmanager. However, admin seems to return usertype=landmanager. This probably doesn't matter for aesthetics but if you are using the usertype variable for functionality elsewhere it could be a problem.

**Comment by coherit** [comment]
maybe related to order of operations wtih 

```
elif user_is_land_manager(request.user):
        user_type = "landmanager"
    elif request.user.is_superuser:
        user_type = "admin"
```

**Comment by mradamcox** [comment]
Ok good catch. I have a feeling this is not really an issue anywhere, but making the change you suggest above is a good idea. To prepare for it, could you make css classes for "admin" which are the same as the default/anonymous? (default/anonymous style is what's currently used for admin accounts). It's a little repetitive, but would allow that change to be implemented sometime soon with the best results.

**Comment by coherit** [comment]
Will do above. One other issue -- the login.htm template is set to use the conditional style sheets based off of {{ login_type }} since user_type = anonymous until you login. Because this template is extending the base template, the body class is already set (body.body-anonymous). Unfortunately, login_type is either hms or state (not scout/landmanager) so I can't use that as a substitute. 

I can either: 
1. leave this template to use the conditional css to get the colored body backgrounds
2. remove the conditional css call and just have the login page default to anonymous aesthetics
3. remove the conditional css call and do some gymnastics with if statements on login_type to get a few aesthetic shifts, but I won't be able to achieve the body background (probably not worth it)

**Comment by mradamcox** [comment]
The login page is actually the most important for these conditional styles, so 2 is out, and I'd really like to get this improvement everywhere so I'm going to say 1 is also out. It sounds like syncing the login_type (hms/state) with user_type (scout/landmanager) would really be the best solution, right? If so, in the interim (and this is again a little repetitive) how about duplicating the scout/landmanager CSS classes to hms/state classes and then using {{ login_type }} in this template? Like the above solution, this would achieve what we need right now, and would allow a seamless transition later when the login_type and user_type values are synced. The extra CSS classes can be deleted then.

**Comment by coherit** [comment]
Good to know -- I think I can do this if I also make the body tag be an editable portion of the fpan-base template. Let me see what I can do.

**Comment by coherit** [comment]
Okay, I think this is all implemented in https://github.com/legiongis/fpan/tree/198_css_loading  

I made admin and anonymous classes, so hopefully this will all work when admin changes from landmanager to admin user_type.

I also fixed a minor list issue with the state_footer_links on the login page -- took away the bullets and centered the logos. Should look better now.

**Comment by coherit** [comment]
@mradamcox Do you want me to address the issue in  https://github.com/legiongis/fpan/blob/master/fpan/utils/context_processors.py#L47 within this issue/branch?

**Comment by mradamcox** [comment]
Well, this is funny actually: https://github.com/legiongis/fpan/blob/master/fpan/utils/permission_backend.py#L29. Seems like this change is ripe to be made... I'd say go for it, and I'll test it out when you have it ready. I've just been looking at the css branch and it's great to have this finally fixed :)

**Comment by coherit** [comment]
Okay, I think I fixed all css issues and addressed the user_type issue by changing the order of the conditional. I checked all the other places where you use user_is_land_manager and you had already provided switches for superuser (or it appeared irrelevant based on superuser permissions anyway). I'll make a PR so you can test and review
