### ISSUE TITLE
Update report to better display recorded Scout Reports

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#207]
Currently the resource reports for Archaeological Sites, Historic Cemeteries, and Historic Structures have a section at the top that lists the Scout Reports that have been entered for that site. This list was never properly formatted after recent upgrades, so it still looks like this
![image](https://user-images.githubusercontent.com/10427268/126850647-ad452134-cb52-4c66-a85b-68524e580f6c.png)

Some general CSS updates are needed to better align this content.

**Comment by coherit** [comment]
In branch https://github.com/legiongis/fpan/tree/207_report_list_css I've positioned the related reports section as seen in the following screenshot. My memory is that these used to be centered in the screen, but my inclination with this report style was to align with the rest of the content below. If you prefer the related reports to be centered, I can do that instead, no problem.

![image](https://user-images.githubusercontent.com/3217017/128609248-2539c9ff-557f-40f4-8a63-41989ea2a618.png)

**Comment by mradamcox** [comment]
I'd say this looks great. @kkemp85, what do you think?

**Comment by kkemp85** [comment]
@mradamcox Yeah I think leaving it left-justified is fine, I think my only concern is that the text for the reports doesn't warp weirdly to the second line like in the picture below. I want them to spread out across the page. If we can make that happen that would be great!

![image](https://user-images.githubusercontent.com/54329725/128754258-5e283e60-dc65-4fbd-86ba-59d3d708d05e.png)

**Comment by mradamcox** [comment]
@coherit when you can confirm that text wrapping is addressed for very long usernames (i.e. multiple usernames) then we'll be good to go.

**Comment by coherit** [comment]
Great -- width for this content is now set to 100%.

![image](https://user-images.githubusercontent.com/3217017/129232559-ab3172b8-a68b-40a0-96a2-85cf570f696d.png)

**Comment by mradamcox** [comment]
merged
