### ISSUE TITLE
Drop down list of Scouts for the "Who is this Site Assigned to?" not loading

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#226]
@mradamcox I know we have run into this before but it would finally load. The dropdown list of scouts for assigning archaeological sites isn't loading (in the archaeological site page). I clicked it and played with it and let it sit for about 10 minutes and it still never loaded.

**Comment by mradamcox** [comment]
@kkemp I had to add a lookup to handle the new Management Area names, and looks like I had forgotten two regions (West Central and North Central). I'm guessing the site(s) you were testing were in one of those regions. Everything should work now. Can you close this ticket when you confirm it's fixed? Thanks!

**Comment by kkemp85** [comment]
@mradamcox the site was in the Northeast region but whatever you did fixed it!

**Comment by mradamcox** [comment]
Ah. Disconcerting, but we'll take it.
