### ISSUE TITLE
Advanced Search not working

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#230]
As discussed with @mradamcox, many facets in the Advanced Search aren't working correctly. They aren't properly filtering results and won't allow you to remove the facet once you add it. Some facets won't even open when you try to click on them. Some, like the page below, have clear rendering issues as well. The problem affects all resources but only some facets within those resources. 

<img width="721" alt="image" src="https://user-images.githubusercontent.com/54329725/150227128-ef462273-628c-4b07-b0e8-a5e315b322cb.png">

**Comment by mradamcox** [comment]
Ok, I've sorted this out. There were actually quite a few errors on different nodegroups, but the one in the screenshot stemmed from the custom widget/datatype combos that we use to reference the management areas and agencies. Similarly, there was an error with the username dropdown that is used for the visiting Scout ID(s) node in the Scout Report.

@kkemp85 I've tested around and Advanced Search seems to be fully functional now. I'm going to close this ticket, but feel free to reopen if you find a non-working nodegroup that I missed.

In fixing this I came across a few ways these custom widgets/datatypes could be handled better, so I'll make a separate ticket for that, for down the road.
