### ISSUE TITLE
Admin dashboard not working/incomplete

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#237]
The admin dashboard where I used to be able to download a CSV file of Scout profile information no longer works. It gives me an error 404 message. I know there is now the ability to download a CSV file of scouts from my admin dashboard, but it doesn't include their entire profile (the open text sections are missing). I need to be able to pull entire scout profiles off of Arches.

**Comment by mradamcox** [comment]
@kkemp85, yeah, the dashboard content was all moved into the profile page. Nothing has changed about that download CSV, so maybe I just need to add that those open text fields to it? I just tested from the admin profile page, and though the CSV did download correctly, the spinner just kept spinning (annoying) so that's another little thing to fix.

**Comment by kkemp85** [comment]
@mradamcox yes I think that's all that will need to be added, those are the only things I see missing in the file when I download it! They used to be on the old one which is weird. And yes, the spinner kept spinning on me as well but I thought it was just mine.

**Comment by mradamcox** [comment]
@kkemp85 These are the current columns in the export file. Would you like me to change the order or rename any at this time? I'm inclined to clean up and capitalize the names as shown below, if that won't break anything. I'll also add the `Education/Occupation`, `Relevant Experience`, and `Interest Reasons` columns (as requested above), so let me know where to put them, or I can just put them on the end.

```
scoutid --> Scout ID
first_name --> First Name
last_name --> Last Name
email --> Email
street address --> Street Address
city --> City
state --> State
zip --> Zip Code
phone --> Phone
interests --> Site Types
region_choices --> Regions
date_joined --> Signup Date
```

**Comment by kkemp85** [comment]
@mradamcox yes this order works. And yes, let's add the new columns at the end.
