### ISSUE TITLE
Region Choices not showing up properly in Django for new scouts

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#264]
I noticed that when new Scouts sign up, their regional choices are not showing up in the normal section. At first, I thought their choices were missing completely (which is strange since it's required for them to submit the form) but upon further inspection, the choice is showing up in the "FPAN regions" section below (see image). What's weird is I've never seen this before AND that section has a lot more in it than the FPAN region choices, meaning to make sure I get all the regions they've selected I have to scroll through the entire list.

![image](https://user-images.githubusercontent.com/54329725/226465743-745e0adf-b8d9-4518-b99f-4dad81373cd4.png)

**Comment by mradamcox** [comment]
Sorry for the confusion here, but this is a result of our consolidation for the Management Area system. Regions are now in with all of the other Areas, so the selection shown above should properly implement the region choice as it pertains to the available scout dropdowns. Once we can confirm everything is working with the Region choices field left blank, then I will delete that field altogether.

**Comment by mradamcox** [comment]
Things to change here:

- [x] Display name in scout signup should not be compound name
- [x] Filter FPAN Regions field in Django admin to only show FPAN Regions (not _all_ management areas)
- [x] Remove old field

**Comment by mradamcox** [comment]
Looks like this was addressed not too long after this ticket was created, just I just didn't link the commit or PR here. Closing now.
