### ISSUE TITLE
"Change Password" link in profile not working

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#274]
I got an email from a Scout who was trying to change their password from their profile page (so they are already logged in). The pop-up came up and she filled it out and pressed "Change Password" but nothing happened. It seems like the prompt to refresh and update her password is not working. 

![image](https://github.com/legiongis/hmsf-md/assets/10427268/6bc6f729-b2b7-4133-8e86-25099e65c268)

**Comment by mradamcox** [comment]
No errors in log, but looks like the form posting creates an "unauthorized" error in dev tools. I will need to look further upstream into this to figure it out.

**Comment by mradamcox** [comment]
Figured this out, it was a problem with the `/auth/password` url matching. I had a url defined for `/auth/` which matched that pattern with any other paths that have the same prefix. So, the post to `/auth/password` was matching the wrong view class and that's what caused the error.

**Comment by kkemp85** [comment]
Just received an email from a Scout that this isn't working again. She said she got an error message. I tried it and it gave me an error message when I tried to submit my email for password recovery.

**Comment by mradamcox** [comment]
I've made a new ticket for this and recorded the solution there, because the email recovery works a little differently: https://github.com/legiongis/hmsf-md/issues/306
