### ISSUE TITLE
Listing for Modules on Scout Pages, can we remove?

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#285]
An intrepid new scout found that if they click on the FPAN sun at the top left of the arches homepage, it brings up a more explanatory menu with a section that says "Modules". Since we call the different classes they take in the new Scout Portal modules, she thought she could click on them and go to our new training course. You could see why this is confusing. Is it possible (or easy) to remove this heading from Scout accounts to eliminate this confusion? If not, not a big deal, I doubt it's something other scouts will find an issue with once we link to the Portal on our landing page.

![image](https://github.com/user-attachments/assets/4da8c454-27d4-4349-a012-a921d2d9cd7b)

![image](https://github.com/user-attachments/assets/3f2ee5cd-93e6-489d-a8fb-2b53a18087d5)

**Comment by mradamcox** [comment]
No problem, I've just removed that Modules header altogether.

**Comment by kkemp85** [comment]
Thanks Adam!!
