### ISSUE TITLE
Add additional map layers

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#30]
Ideas for this include:

- [x] - the sea-level-related layers already in use in the original HMS map
- [x] - historic map from 1919 showing the coastline (west side only)
- [x] - fpan region overlays
- [ ] - FL county overlays

**Comment by rosulliv14** [comment]
Could we also include a layer with State Park boundaries?

**Comment by kkemp85** [comment]
@mradamcox I believe can make all these layers in our new Mapbox map I am creating. The only thing I want to double-check is if I add in a tile of the FPAN regions, that will show up as an overlay that can be turned on and off right? That isn't something that needs to be on all the time. But, the county boundaries should always render on the map, or I guess, be set to automatically be on when a scout logs in. If that's possible, I can close this ticket and do this myself.

**Comment by mradamcox** [comment]
@kkemp85 If you want a layer that can be turned on and off separate from the basemap, then you will have to make that layer a separate "style" in mapbox. Then we'll be adding each style separately to Arches.

**Comment by kkemp85** [comment]
@mradamcox Ok that's easy enough. I will do that and close this ticket
