### ISSUE TITLE
Scout data and site labels

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#39]
This is more of a musing than a specific problem that needs to be fixed.

As I understand it, each sites is labeled with FPAN regions and basic site types. This information is also included on the scout application. In order for me to be able to assign a scout an archaeological site, the scout must have selected the corresponding region and site type. Let me know if I'm correct because if not, what follows wouldn't quite matter.

So a few musings and questions:

- I can see that we may run into issues with wanting to assign a site to a scout who doesn't have the correct boxes checked. If this keeps being an issue, do we then just end up with all scouts checking all boxes? (Which is something that happens often enough as is) And at that point, does the system ceases to be helpful in sorting things? 
- Should we think about more meaningful labels for archaeological sites than just general prehistoric, historic and underwater? Is it worth removing cemeteries from the list as everyone already sees those.
- Is this data still useful to us in general to see where our scouts' interests lay? I use the region to sort for our email lists.
- I know the whole system uses tags and labels to sort things, so I can see that this structure is also just how Arches operates. I could be overthinking it all.

This may be an actual action item: the option of "other" isn't meaningful without the option to type in what other may mean. I assume it may also be useless in terms of site types. We probably should remove in general.

**Comment by mradamcox** [comment]
Hey @emjaymur, you're right that each site has a site type and region attached to it, however only the region designation is used to filter scouts. When a scout fills out their profile and says they are interested in a type of site, they are not restricting their access to other sites, just recording their preference. So in the assignment dropdown, we included the site type preference for you as admins to be able to take into consideration, kind of just an FYI. All that to say:

+ a scout cannot be assigned to a site outside of the regions they have checked the box for in their profile
+ a scout can be assigned sites of any type no matter what their site preference is

As for the categories themselves: all of the attributes for the site records come straight from FMSF. So "other" in the HMS database is "other" in FMSF. That said, in the RDM (reference data manager, hms.fpan.us/rdm) you would be able to add more categories to the site type, and those would appear in the dropdowns for an admin that is editing a resource.

Feel free to experiment with that, but if you want to make a permanent change now (during development) also let me know, so I can change some of the backup files.

**Comment by mradamcox** [comment]
@emjaymur do you think we could close this ticket? If you have decided that some new functionality would be beneficial, it would be best to create a new ticket and describe it there.
