### ISSUE TITLE
Map View Options

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#40]
Could we set the standard map view where it does not show the hexagon overlays and markers for the top sites? Mostly wanting to see if that's an option. Is there a good reason for keeping them? (not to sound snarky, just wanting to know if there's some other function of them that I'm missing)

Discussion for FPAN to have: I think it's easier to view and navigate without the hexagons. I think the search markers are confusing (I couldn't figure out why some sites had those but most didn't until Adam explained it.) Would we want to ditch this? I'm just thinking how to simplify interface.

**Comment by rosulliv14** [comment]
I agree on the no hexagons. I'm pretty sure that is one of the options we can switch on or off in the Uber Admin section if I remember correctly

**Comment by mradamcox** [comment]
Ok sounds good. There is another issue with the hexagons that I logged in the main Arches repo a while ago: https://github.com/archesproject/arches/issues/2820
I just did it, but deactivating the Hexagons happens in the Map Layer Manager > Overlays > Search Results for future reference.

**Comment by mradamcox** [comment]
I also agree that the Search Markers layer is a little confusing at first, but would advocate for keeping it because otherwise there is nothing that links the map markers with the search results. In my mind, the actual best would be if the full layers could be altered to only show the search results, but that is not supported at this time.

**Comment by mradamcox** [comment]
@emjaymur If you are ok with leaving the markers on, could you close this issue, and if not, we should discuss it further here.

**Comment by emjaymur** [comment]
The map is much easier to navigate without the hexagons. I think the markers make a lot more sense now, so I'm good to leave them.

**Comment by emjaymur** [comment]
I can set this up as a whole new issue, but I am now having issues with viewing archaeological sites that I've added to my account. They show up with the markers, but the overall shape of the site does not show up, as it does while in the admin account.
![map view arch site](https://user-images.githubusercontent.com/37811747/38831850-ab822d68-418e-11e8-89f8-5885ea9e0a94.jpg)

**Comment by mradamcox** [comment]
Yes, it would be best to make a new issue for this and close this issue.
