### ISSUE TITLE
Site Information Page

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#41]
These are changes to the page that comes up when you click on the name of a resource. 

Can we change the Search icon and hover text? Maybe "Database Home" (or just "Home") and a house icon?

When I get to the main page with the site basic site information, there's this "Edit Mode" bar at the top of the map. Is there a way to get rid of that? It doesn't do anything but makes it look like I have more power than I do. I can see where some folks will be nervous that they may accidentally change things.

![edit mode expanded](https://user-images.githubusercontent.com/37811747/37929359-c7903342-310d-11e8-9e5b-3bd8fb1c3f72.jpg)
![edit mode minumized](https://user-images.githubusercontent.com/37811747/37929360-c7a26f6c-310d-11e8-8ea8-af51f01eec9d.jpg)

**Comment by mradamcox** [comment]
https://github.com/archesproject/arches/commit/03207b8e0a77e456691889cd039bbf4a0d8ad0c1
