### ISSUE TITLE
Search Page edits

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#42]
In the left column, each resource has it's own little box. Can you change the "Edit" text and icon? To keep things consistent, let's use "Log Visit" and the little guy that you have as an icon on the individual resource pages.

How is the "Recent Edits" supposed to be used? Do we need to keep that there?

![main page](https://user-images.githubusercontent.com/37811747/37929730-c100cf72-310e-11e8-9ba0-e6a2aa053b82.jpg)

**Comment by mradamcox** [comment]
@emjaymur it shouldn't be too difficult to change the icon.

As for the Recent Edits page, in the version of Arches that HMS uses (4.0.1) that page actually doesn't hold a whole lot of information, I think we would be safe to remove it. Here's some more reference on the work that has been done on the recent edits page more recently https://github.com/archesproject/arches/issues?utf8=%E2%9C%93&q=is%3Aissue+recent+edits+is%3Aclosed+
