### ISSUE TITLE
Related Resources

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#43]
Just wondering how this feature works. Will it link sites that are related based on FMSF data? For instance, linking the files for a cemetery, a structure and an archaeological site all labeled as Nombre de Dios? Or does this somehow build links between similar sites? Right now, nothing I've click on seems to have anything related to it.

**Comment by mradamcox** [comment]
@emjaymur Great question. Related Resources are a feature of Arches that allow for qualified relationships to be created between any two resources in the database. In the past, I've had a cemetery dataset, where each interred individual was a resource, as well as the grave, and they were connected to each other with resource-to-resource relations. In the case of FPAN, we considered relationships between resources as an early strategy for connecting scout reports with resources, but the permissions restrictions necessary to make this work were not in place. So, ultimately, we have this disabled, and I have been planning to remove that section from the reports, so it's invisible. If you want to experiment with how to create resource relationships, begin editing a resource, and then click the ? help tab in the top right. There's quite a bit of info in there about Related Resources.

**Comment by mradamcox** [comment]
@emjaymur if this is a satisfying answer would you mind closing this ticket?
