### ISSUE TITLE
New Windows Opening

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#44]
Each time I select a resource, Arches opens a new window. And then I end up navigating back to the main map in that window. So before I know it I have 18 different windows open. Just wondering if that's a feature we can turn on and off.

**Comment by mradamcox** [comment]
It is something I should be able to change relatively easy. I'll leave it as low priority now though, in favor of other issues.

**Comment by mradamcox** [comment]
https://github.com/legiongis/arches/commit/deadc98e683d1024dc58b920d5b34ce37dae6cc3
