### ISSUE TITLE
Scroll Issues in Firefox

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#45]
On the page for logging scout reports, I can't scroll vertically when using Firefox. It will scroll horizontally. It seems to work just fine in Chrome. I tried clicking through all of the options (Site Summery, Site Location and Scout Visit) but it doesn't work for any of them. Haven't noticed on other pages but will update if I do.

![scout report](https://user-images.githubusercontent.com/37811747/37931844-e8942736-3114-11e8-8fbf-e9afd6bfc9f4.jpg)

**Comment by mradamcox** [comment]
@emjaymur unfortunately, this is still a limitation of Arches in general: it is only 100% supported on Chrome. However, progress is being made on that front so we will eventually be able to incorporate those changes into HMS.

Looks like someone just made this issue on the main Arches repo also: https://github.com/archesproject/arches/issues/3171
