### ISSUE TITLE
Edits to Scout Report Form

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#46]
Here's a few comments, questions and edits for the Scout Report itself.

- Remove "Type of Visit" Initial or Follow-up
- Is there anyway to include a specific time stamp for time of day? 
- Can we add "Shell Midden" to the "Artifacts Visible" section? What about adding "grave markers" and/or "grave goods?"
- Should "Overall Site Condition" be moved to "Report Evaluation?"

**Comment by mradamcox** [comment]
@emjaymur I am moving this to the fpan-data repo, where all of the resource model definitions are stored.

**Comment by mradamcox** [comment]
This issue was moved to legiongis/fpan-data#6
