### ISSUE TITLE
Non-User database access

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#47]
As it looks now, people without usernames can still see past reports and photos. They can only see cemeteries and structures, so they shouldn't be able to see anything too sensitive. While this could be good persuasion for others to join and start monitoring themselves, there could be a situation with images of exposed human remains posted online publicly, for instance.

So:
- Is there a way to remove scout reports from unlogged-in viewing?
- Is this something we want to do?

**Comment by mradamcox** [comment]
@emjaymur with the current resource model setup, excluding from public view _some_ cemetery and structure scout reports but not all would be very difficult to do. Though I do understand the desire to do so. It may be best to just make sure that scouts don't upload photos with human remains for now.

I have been working on a new structure to separate the scout reports into a different resource model altogether, which would make this task much easier to handle. More on that update in the future...
