### ISSUE TITLE
Phone Interface Issues

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#48]
These may be bigger issues than you, Adam, but wanted to log my issues with the phone interface.

- You can scroll around on the map on the search page but you cannot select a resource by tapping on it. It just manipulates the map.
- The scout report page doesn't show up correctly. Everytime I loaded it, the"Print Assessment Form" text link shows up on top of the first two tabs (Arrival Information and What did you find or Structure Details depending). Sometimes the full list of questions didn't load and continued to not load even after refreshes.
- This is the big one: I can't get photos to upload from my phone. I end up with a load screen swirling for an absurdly long amount of time and then abandon all hope. I tried it on cellular data, on a public wifi network at a restaurant and from our office, which has private, fast and stable wifi. I tried using photos from my library and taking one during the upload process (it gives you the option on phones). I tried from my work iPhone and my personal Android. It may eventually load, but I don't expect anyone to sit there for that long waiting. The worst part is you have to start completely over with the scout report - there's no way to abort the upload or go back or anything like that.

**Comment by mradamcox** [comment]
First, can you confirm that you are using Chrome on the table/phone? By and large, the phone interface will always be clunky, as that is what the mobile app will handle in the future.

I'll see what I can do about these issues though. The photo upload is a real concern, I'm not sure why it would be failing like that, so I'll check it out as soon as I can.

**Comment by emjaymur** [comment]
I tried Chrome - works better. I was able to navigate the Scout Report a little easier. I think a lot of it does have to do with your cellular reception. But it's still not working to upload photos. It just gives you the spinning wheel of death.

**Comment by mradamcox** [comment]
@emjaymur Ok, I have been testing the photo upload on mobile, and I think things are working ok now. Unfortunately there is no upload progress bar after you hit "Add" to add a photo, and the spinning wheel of death may just spin for a while because it is taking a long time to upload a photo. It seemed to take longer to upload a photo from my phone than from my laptop (not sure why).

**Comment by mradamcox** [comment]
I did encounter an internal error which would have caused the death wheel to spin forever, but after fixing that I then got a timeout error (red bar across the top of the page) the first couple of times I tried uploading (after waiting a while). So I just increased the timeout limit on the server and was able to upload a photo. If you could try again and just be very patient with the upload, we'll see if that works. As for the print link, I see what you mean about the bad placement, and will look at that now.

**Comment by mradamcox** [comment]
https://github.com/legiongis/arches/commit/006af8fa8221789627e81f9ffb8ef3e0d91c92b4

**Comment by mradamcox** [comment]
@emjaymur all 3 of these issues should be fixed now:
- [ ] map popup works when viewing map on mobile
- [ ] "Print Assessment Form" button better spacing
- [ ] photos upload without erroring (though it may take a little while)

Once you are able to test these things out, could you please close this issue if everything works ok? Thanks!

**Comment by emjaymur** [comment]
I'll test these out tomorrow and will get back with you. Thanks!

**Comment by emjaymur** [comment]
Ended up trying it out this afternoon after all.
- The dialogue box still will not open when I click on a resource on the map.
- "Print" definitely better spaced
- Photo uploads - Tested it out on wifi and cellular data and it worked well on both. It of course, works better on wifi, but I'm pretty sure I have Sprint to blame for that. I can't seem to be able to go back into the uploaded sections to add more photos, but this is something minor we can live with. Yay!

**Comment by mradamcox** [comment]
Ok, for the map popup, I think you may need to refresh your browser cache. The method for this will be different depending on whether you are on an android or iphone, but this seems like a good trick https://android.stackexchange.com/a/88713.

**Comment by emjaymur** [comment]
That worked! :-D
