### ISSUE TITLE
Timestamp for Dashboard

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#52]
Could you add a timestamp column that reflects when scouts created their accounts to the tabular user data that is downloaded from the Dashboard page? It will be easier to differentiate new users when uploading names to MailChimp. It will also help us track users for our annual reports. Thanks!

**Comment by mradamcox** [comment]
@emjaymur can you check the status of this? I think it's been addressed.

**Comment by emjaymur** [comment]
It has. Thanks!
