### ISSUE TITLE
Add publicly interpreted sites to scout accounts

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#54]
We'd like to add a set of publicly interpreted and accessible sites as a default to all scout accounts. I'll attach a draft list of sites to play around with sometime this week.

**Comment by emjaymur** [comment]
Here's a couple of sites to play with for creating the public layer. I can get a more formal list, but it will take a little time to reach out to other regions. 

[Archaeological Sites for Public Layer.docx](https://github.com/legiongis/fpan/files/2318719/Archaeological.Sites.for.Public.Layer.docx)

**Comment by mradamcox** [comment]
Current thinking is to add an attribute to the site resource model, so that the db admin can update it just like they would assign a scout.

Here's the updated list: 
[Archaeological Sites for Public Layer - final.docx](https://github.com/legiongis/fpan/files/3527722/Archaeological.Sites.for.Public.Layer.-.final.docx)

**Comment by mradamcox** [comment]
There is now an option to "assign" a site to "Public Access" this should allow anonymous users to view those sites, and create new scout reports for them. The whole process could use more testing though. I'll leave this open until @emjaymur can confirm things are working well.

**Comment by mradamcox** [comment]
Problem brought to me by @kkemp85: because the access is currently keyed off of the username (`anonymous`), when scouts login they are no longer able to see the public site. Public sites must be available to all scouts and land managers.

**Comment by mradamcox** [comment]
This is now handled for Scouts (fix will be deployed tomorrow morning).
