### ISSUE TITLE
Creating new sites

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#57]
Is there a simple and easy way for us to create new sites? Or is this something best left up to an annual update and based on the FMSF data? (The assumption is that we would also be adding to the FMSF at the same time.)

**Comment by rosulliv14** [comment]
You can create new sites when you are signed in on the admin account, you can draw in the geometry and manually enter the site info - although probably easiest to add lots of sites when we get the annual FMSF updates I'm sure

**Comment by mradamcox** [comment]
@emjaymur and @rosulliv14 , if we want to maintain a correlation with the FSMF, I think it would be best to wait until the periodic updates to add more sites, even you can add them as becky described above.

**Comment by emjaymur** [comment]
I think that sounds like the best option as well.
