### ISSUE TITLE
Advanced Search Feature

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#60]
Some of these features do not work for scout accounts. For instance, I can search for cemeteries by county by going to Identification and searching FMSF ID Like using the two-letter county code. This will work in the admin accounts and the FPAN regional accounts (that have BAR credentials). It will not work for a scout account.

**Comment by mradamcox** [comment]
Good find @emjaymur. This certainly has to do with the permissions handling that I have set up to restrict scouts from seeing all sites, so I'll look into it when I get a chance.

**Comment by mradamcox** [comment]
I'm fairly sure this is the same issue as #73, which should be addressed by #116.
