### ISSUE TITLE
AP site issues

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#61]
It looks like a few Aquatic Preserves were overlooked in the account creation. I was able to make an account for Charlotte Harbor APs and add it to the Aquatic Preserve group. However, the sites they manage down near Fort Meyers are not in the list of AP sites. The total number of sites for APs is 249 in Arches - but there's at least 200 in the Charlotte Harbor APs alone. Should I check with the State to see if they have a list of all sites in the APs? I think one of our staff, Kassie, may have had something like this.

List can be found in their management plan, starting page 222: http://publicfiles.dep.state.fl.us/CAMA/plans/aquatic/Charlotte-Harbor-AP-Management-Plan.pdf

**Comment by kkemp85** [comment]
@mradamcox this ticket is directly related to issue #64  so they should be combined.

**Comment by mradamcox** [comment]
Closing in favor of #64
