### ISSUE TITLE
Site Form bug and edits

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#63]
Can you change the wording on this site location option, under the "Arrival Information" tab?

"Mission location verified" to "Site location verified"

The "What did you find?" section seems to have gotten a little out of order. The blank space for to write in info about artifacts has migrated to the top of the page instead of being underneath the "Other" option. The section for comments on site impacts should also be at the bottom.

**Comment by mradamcox** [comment]
Hi @emjaymur , you should actually be able to make both of these changes yourself. Log in with the administrator account and then go to the Arches Designer > Resource Models, and ultimately you are looking for the Card Designer. In there you can change the names of the cards that users see, and you should also be able to change the order of the items. Let me know if you have any questions!

**Comment by emjaymur** [comment]
Hey @mradamcox. Thanks! I was able to rearrange everything but couldn't change the text on the Location Verification options. Am I missing something else?

**Comment by mradamcox** [comment]
@emjaymur If you look in the Card Designer and then click on the left-hand tree to select the "Scout Visit Location Verification" widget, you should be able to change the label. BTW, this whole graph design system is much much better in the more recent version, so it's good that we'll be updating.

**Comment by emjaymur** [comment]
@mradamcox I can see where you change the widget label but I wanted to change the options for answers and don't see how to make those editable.

**Comment by mradamcox** [comment]
Oh! Gotchya. Yes, you can head over to the RDM (also on the left side-bar) and that's where the controlled vocabularies are. Dropdown entries are considered "Concepts". If you just want to change the display label of a concept, that's pretty easy. If you want to add a new concept to a dropdown, first create the concept in the thesaurus, and then add it to the appropriate collection. Use the ? button in the top-right for more info.

**Comment by emjaymur** [comment]
Wooo! I got it changed. Thanks!! :-D

**Comment by emjaymur** [comment]
Hey @mradamcox I've reordered the forms multiple times - and hit save! - but they keep reverting to the same out-of-order state again. Any thoughts?

**Comment by emjaymur** [comment]
Hey @mradamcox I tried to reopen a few months back but I don't think it worked. I've reordered the forms and it doesn't stick. So it's still out of order. Any thoughts?

**Comment by mradamcox** [comment]
Hey @emjaymur sorry for missing this earlier. I think that that's an issue with Arches that has since been solved with later updates. Which we'll be applying in the FPAN update! In fact, that backend graph designer portion of Arches has been significantly redesigned, so I'm looking forward for you to get to check it out.
