### ISSUE TITLE
Order of past forms

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#66]
Hey @mradamcox. We have someone working on entering our backlog of scout reports from the old Google Form system. I've noticed that the reports for the sites sort by date of entering, so for some sites there is no good order for the forms in terms of when the monitoring actually happened. Shell Bluff Landing is a good example if you want to see what I mean. Is there a way to resort them by the form date? Thanks!

**Comment by mradamcox** [comment]
@emjaymur This will essentially be a non-issue once the upgrade is complete. At least, if it's still an issue it will need to be handled very differently than it would be at this time.

**Comment by mradamcox** [comment]
This is now handled with the recent update: 
![image](https://user-images.githubusercontent.com/10427268/68673758-14888000-051a-11ea-8f48-b477773164cc.png)
