### ISSUE TITLE
Arches Landing page analytics

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#67]
We are trying to track visits to the Arches landing page for future reporting. Our FPAN website manager said that we could probably request that info from you, but it's also possible to get that info ourselves if a bit of code was added to the page and we provided you with our Google Analytics tracking code. Is this something you could do for us?

**Comment by mradamcox** [comment]
@kkemp85 I think I can do you one better :) I'll e-mail you.
