### ISSUE TITLE
Update Links for Creating a New Report

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#70]
Currently, the icons and buttons used to create a new scout report are pretty buried, and confusing, especially to users who have experience with the prior iteration of the database. Two main actions should solve this:

1. Change the top menu icon of the walking man (titled "Log a Visit") back to the default edit pencil icon and title it "Edit".
2. In a resource report for Archaeological Site, Historic Cemetery, and Historic Structure, add a button under the "Reports Recorded for this Site" section titled "Create Report" which takes the user directly to the resource editor for a new Scout Report.
![image](https://user-images.githubusercontent.com/10427268/68674949-7944da00-051c-11ea-8928-a5f781cce880.png)

**Comment by coherit** [comment]
Both of these items have been addressed in commit 2e3d09d:

1. Anyone who has permissions to edit a resource now sees the pencil and "Edit"

2. A hard coded button has been added in the designated spot to take the person to "add-resource/14578901-bd5d-11e9-822a-94659cf754d0" -- a new scout report (using the uuid in the package). This will break if the uuid changes for some reason.

**Comment by mradamcox** [comment]
ok great, I'll be staging this change and the others momentarily for review. The UUID won't change, so we're good on that front.

**Comment by mradamcox** [comment]
@kkemp85 We now have this change live on the staging server, which is http://fpan.legiongis.com. Could you check it out and close this ticket if you think it's been resolved?

**Comment by kkemp85** [comment]
@mradamcox The "create a report" button is perfect!! and I'm so glad the walking man is gone and has been replaced with the logical pencil for editing! This will make it much easier on our scouts and even the FPANers too. Looks great!

**Comment by kkemp85** [comment]
@mradamcox looks like you will have to close this one, won't let me since you created it.

**Comment by mradamcox** [comment]
@kkemp85 I'll add you to this repo as a collaborator, then you should be able to close tickets, etc.
