### ISSUE TITLE
Mac display Issue

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#71]
A few of our Mac users have noticed a weird display issue where all the features overlap each other and seem jumbled on the home page and other pages. See the image for an example (the map has been purposefully blocked out).
<img width="719" alt="Mac Issue" src="https://user-images.githubusercontent.com/54329725/69261917-8010c400-0b90-11ea-941a-e666f9290b58.png">

**Comment by mradamcox** [comment]
The first thing to make sure of is that everyone has cleared their browser cache. Here is some information on the easiest way to do that: https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/ It's possible that a few people haven't done it and they have macs... At least, I'm hoping. If that doesn't work, then I'll look into this on a mac.

**Comment by mradamcox** [comment]
@kkemp85 can you double-check that this is still an issue for everyone and close if not?
