### ISSUE TITLE
Archaeological Site polygons not visible in map

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#72]
On accounts that have access to any archaeological site, a scout that is assigned one site or an admin account that can see all sites, the archaeological site polygons are not rendering on the map. This makes it extremely difficult to search an area for a site. On my admin account, I can still search sites if I know the site number, but the polygons don't show up, just the black marker showing the search location.

**Comment by mradamcox** [comment]
@kkemp85 can you confirm that this is all solved for all of the use cases that we need?

**Comment by kkemp85** [comment]
@mradamcox Well, they were all working on all accounts but this morning we checked and all the FPAN regional accounts and my HMS Database login (which I never use) are missing the archaeological sites again. And not just the polygons this time, but also the site listings. The results should have around 39,000 sites, but they only have around 5,359, the same number all the regular scout accounts can see - which represents just cemeteries and structures. So something happened since last week. I looked in the permissions area and everything is set up correctly and the same as it was from what I can tell, so not sure what happened. I checked all the other types of accounts I have access too, state park, forestry, fwc, and normal scout accounts and they look fine. Not sure about ones like the BAR or FMSF ones though since they changed their passwords.

**Comment by mradamcox** [comment]
@kkemp85 Ok, I remember now you said earlier that there was an issue with the State District manager accounts, is that still true?

**Comment by kkemp85** [comment]
Yes! Thank you for reminding me. I just looked at all those again and all 5 district accounts are having the same issue that we were having before with the state accounts. All the archaeological sites these accounts are supposed to have visible are showing up in the results, but the polygons are missing. For some reason, archaeological sites in Terra Ceia SP are showing up in the SPDisctrict4 account, but only those, not the rest of the SP sites.

**Comment by kkemp85** [comment]
Hey, @mradamcox just wanted to let you know that this is still an issue as outlined in my long comment above. I also got word today that the BAR account can't see the polygons either. I can't log in to that account since I don't know the password but I'm assuming it's the same issue we are seeing with the other accounts. Thanks!

**Comment by kkemp85** [comment]
@mradamcox  We need to add the land manager accounts to this issue now as well. I logged into state park, FWC, and forestry accounts and they are all missing archaeological site polygons, even the structure and cemetery ones are missing. 

Another possibly related issue is that the links to site details aren't working, it gives an "Error 500" when I click on any of them within these accounts. This isn't an issue in my admin account, the links are working fine. 

![image](https://user-images.githubusercontent.com/54329725/72831097-23915a00-3c50-11ea-95f4-34d92b1f40e3.png)
