### ISSUE TITLE
Search issues with new Arches update

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#73]
We have noticed some issues searching archaeological sites within scout accounts and general accounts like the FPAN Northeast account. Not only are the archaeological site polygons not showing up (detailed in a different issue) but also users can't even search for archaeological sites. The site number will come up in the search bar but then the results will say 0. One FPAN employee noticed that when clicking on the report for one site she could get to come up when searched, none of the coordinate data was listed as it typically is, not sure if this has anything to do with why they aren't rendering but I thought I would mention it just in case. Admin accounts search sites fine (though the polygons don't show up).
<img width="654" alt="Problem with arches" src="https://user-images.githubusercontent.com/54329725/69263724-e0edcb80-0b93-11ea-9a0f-3b7a991aa256.PNG">

**Comment by kkemp85** [comment]
@mradamcox looks like this is an issue with the SJRWMD accounts as well. All the other Land Manager accounts seem to work fine though. It's a problem since the land managers won't be able to log reports unless they click through all search pages to find the site they want and click on it directly. I notice in my original comment that it says archaeological sites only but this also affects structures and cemeteries as well. This means that no scouts or SJRWMD managers can search for those either. It's been a problem with one of our active scouts who logs cemeteries on a daily basis

**Comment by mradamcox** [comment]
I can confirm that in the Arches 5 update branch I'm working on (which will address #115, and includes the upgrades described in #116) this is issue is no longer present. Will close this ticket after we 1) get Arches 5 in staging for testing and 2) finally deploy the upgrade to 5.
