### ISSUE TITLE
Arches Admin Dashboard link no longer works

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#74]
The link I had to go and download new scout applications no longer works. It gives me an error. I figured this has something to do with the new update and simply just needs to have an updated link to the new location for the excel data I download every day

![image](https://user-images.githubusercontent.com/54329725/69264026-7e48ff80-0b94-11ea-8c26-42f5cb16f4f4.png)

**Comment by mradamcox** [comment]
This is now fixed.
