### ISSUE TITLE
Scout List Export - improve file name

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#76]
The file created from the admin dashboard that lists all current scouts does not have a file extension in its name, it's just `HMS`. It should, at least, be `HMS.csv`, but preferably the date should be added to the name as well.

**Comment by coherit** [comment]
@mradamcox This looks like it was already completed. I downloaded the file from /dashboard as admin and it is named: "HMS all scounts 21-02-20.csv"
![image](https://user-images.githubusercontent.com/3217017/75065664-3c8f6400-54b7-11ea-9c3d-91fbfd62f823.png)

**Comment by mradamcox** [comment]
@coherit strange, it seems to work fine in Chrome, but not in Firefox. In Firefox it just has the first word `HMS` as the entire filename (no extension either). Could you investigate further?

**Comment by coherit** [comment]
@mradamcox Okay, this is fixed now for Firefox. It didn't like the spaces in the filename, so added underscores. Now downloads properly in FF and Chrome. I pulled master and then committed these changes as a new branch: [76_improve_csv_name](https://github.com/legiongis/fpan/tree/76_improve_csv_name)
