### ISSUE TITLE
Adding a line of text to the Arches portal pages  -info on forgotten passwords

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#78]
We would like to add a line of text explaining what scouts should do if they have forgotten their passwords to the login pages for both the Scout Portal and State Land Manager Portal. We realized no language exists right now and it has caused a ton of confusion and creation of additional accounts. We wanted to keep it simple and have the line of text say “Forgot your password? Please email your Scout ID to hmsflorida@fpan.us to reset your password” for the Scout Page and “Forgot your password? Please email your State Agency ID to hmsflorida@fpan.us to reset your password” for the State Land Manager page. We would like the email to be a link they can click on.

<img width="740" alt="1" src="https://user-images.githubusercontent.com/54329725/70360816-8f109b00-184d-11ea-9182-3534cf464a6a.png">

**Comment by mradamcox** [comment]
Part of the Arches upgrade included a reset password form. This was hidden from us, because we had customized the login pages a long time ago. I added a link to the new form and have tested it out successfully. People can now reset their own passwords.

**Comment by kkemp85** [comment]
I’m obviously not supposed to be working but this was too exciting not to reply to. This is amazing!! Thanks Adam!

Sent from my iPhone

On Dec 20, 2019, at 12:08 AM, mradamcox <notifications@github.com> wrote:

﻿

Part of the Arches upgrade included a reset password form. This was hidden from us, because we had customized the login pages a long time ago. I added a link to the new form and have tested it out successfully. People can now reset their own passwords.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_legiongis_fpan_issues_78-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAM6QC7MCAF3WDZ6J6XL74VDQZROMLA5CNFSM4JXCTO5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHL7TCA-23issuecomment-2D567802248&d=DwMCaQ&c=IYmLxukO8P_T_7wP7d_dOg&r=w0jd6TgTnfGlu4QDRQV4V4rfs5FcOSQBzqzXolzYWu0&m=Zy9BPA0mtqiSishPePCioYPKxMZRyFAVhOviphijn_Y&s=cI6vw-uawLwOyAg_Ov2iFlhHgscFVdUe7V0aThLtgQ4&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM6QC7KPRIGFMHMLFEZXIC3QZROMLANCNFSM4JXCTO5A&d=DwMCaQ&c=IYmLxukO8P_T_7wP7d_dOg&r=w0jd6TgTnfGlu4QDRQV4V4rfs5FcOSQBzqzXolzYWu0&m=Zy9BPA0mtqiSishPePCioYPKxMZRyFAVhOviphijn_Y&s=X_xmRl75_WtyPMt7blS1ZTwCLqWsRSlnbzEgaa_yT9k&e=>.

________________________________



This email contains CONFIDENTIAL information intended only for the use of the addressee(s) named above. If you are not the intended recipient of this email, you are hereby notified that any dissemination or copying of this email is strictly prohibited. If you have received this email in error, please notify us by reply email and delete this email from your records. Furthermore, the contents of this email do not necessarily represent official policy of Flagler College.
