### ISSUE TITLE
Changing text on the Scout landing page

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#82]
We would like to change the text for the "How do I log a visit?" section on the scout main landing or home page. As it stands now it doesn't really match the real process. We would like the wording to be this:
How do I log a visit?
1.	To log a scout visit for a Cemetery or Historic Structure, click “Explore the Database”, then in the Menu Pane on the far left of the main map page, hover over the building icon and click on “Scout Report” under the “Add New Resource” heading. Then, follow the detailed instructions to log a visit. _(“detailed instructions” will be a link to the Arches Scout Report instructions once we are finished upgrading the document with new images from the new update)_
2.	To monitor an Archaeological Site, you must first request access to that site. Please email us at hmsflorida@fpan.us to request access or get suggestions on sites you can monitor in your area.
3.	Once an Archaeological Site has been assigned, you can view the site's location and log a Scout Visit by following the detailed instructions. _(again “detailed instructions” will be a link to the Arches Scout Report instructions as mentioned above)._

We would also like to add a new section below it that says "Would you like a monitoring form to take with you in the field?". It will have two bullets below the heading as follows:
-Download the Archaeological Site form (_this will be a link to a fillable pdf_- attached below)
-Download the Historic Structure form (_this will be a link to a fillable pdf_ - attached below)

![image](https://user-images.githubusercontent.com/54329725/70943083-04365a00-201e-11ea-9b06-bbbf72bf4bdb.png)

[Fillable Form Archaeological Sites.pdf](https://github.com/legiongis/fpan/files/3970158/Fillable.Form.Archaeological.Sites.pdf)
[Fillable Form Historic Structures.pdf](https://github.com/legiongis/fpan/files/3970159/Fillable.Form.Historic.Structures.pdf)

**Comment by coherit** [comment]
@mradamcox  The text has been edited with links as requested (the "detailed instructions" links don't go anywhere right now, but you can see how they'll look once the instructions are ready). I styled links to the orange accent color used for scouts so they stand out a bit more. [Commit bfffc2c](https://github.com/legiongis/fpan/commit/bfffc2c76abd4c3add5cd18610db2558787d0880)

**Comment by kkemp85** [comment]
Looks good! It may be a while until I can get those detailed instructions finished so you can link to them just FYI

**Comment by coherit** [comment]
@kkemp85 No problem -- is this the file I should link to for now? [http://fpan.us/uploads/nerc/HMS%20Florida%20Arches%20Instructions.pdf](http://fpan.us/uploads/nerc/HMS%20Florida%20Arches%20Instructions.pdf)

**Comment by kkemp85** [comment]
@coherit Yes! that is the temporary file. thank you!

**Comment by coherit** [comment]
Got it and updated! [Commit e9e4323](https://github.com/legiongis/fpan/commit/e9e43237a972f9cdc2bb16e3acb1caf5794f09d3)

**Comment by mradamcox** [comment]
@coherit Regarding the link colors, I like orange, but would prefer them to not change size on hover. Looking more closely at links across various accounts, I think it's worth a separate ticket which I will write and assign to you. So, we'll close this ticket once the text on the landing page and the links targets have been properly updated.

**Comment by kkemp85** [comment]
Can we move the "Would you like a monitoring form to take with you in the field?" section to the left of the page? It just looks really crowded on the right-hand side underneath the "How do I log a visit?" section. Maybe put a light lined box around it or something to offset it?

![image](https://user-images.githubusercontent.com/54329725/72998498-f1a50280-3dcb-11ea-8871-87ac80acccdb.png)

**Comment by coherit** [comment]
Sure, here's a screenshot of what I did. Let me know what you think. @mradamcox this is in branch issue_82
 
![image](https://user-images.githubusercontent.com/3217017/73283514-34e2e500-41c1-11ea-932a-9ab893120c2e.png)

**Comment by kkemp85** [comment]
@coherit This looks fantastic! Way better than what I was even thinking!

**Comment by kkemp85** [comment]
I finally have the updated "detailed instructions" document for the link at the end of number 1 under "How do I log a visit?". Here is the new link: https://drive.google.com/file/d/1NAnY6n4eLGXE0Vf0Wd-esg0ZeqZWX_SE/view?usp=sharing

**Comment by mradamcox** [comment]
@kkemp85 I'm afraid we lost track of this and I'm only now getting the link to the detailed instructions on Google Drive added.
