### ISSUE TITLE
Cascade Archaeological Site Permissions to Downloaded Data for Collector

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#84]
When creating a new collector project, the admin decides which groups/users are included in the project. When Archaeological Sites are downloaded into the project, they must be filtered in a way that matches the permissions for the groups involved.

**Comment by mradamcox** [comment]
@kkemp85, thinking about this, I think there is actually already a pretty good workaround. In all cases, the site access permissions are driven by queries that can easily be replicated in the search page, in the Advanced Search tab. Then, that url can be used in the project config to determine which sites to include in the project when users download it. For example, if the project is for Tomoka State Park, you would use advanced search with OR statements to find all of the Archaeological Sites, Historic Cemeteries, and Historic Structures that are located in that park. Then copy and paste that url into the project.

The obvious limitation here is scouts of course. There is no way to include a set of sites in a project but then have individual scouts see different sites in the app itself. So, we really can use this for scouts in an effective way at this time.

**Comment by kkemp85** [comment]
@mradamcox that makes sense to me. The priority is on land managers being able to use the app so if scouts have to be on the backburner right now, that's fine.

**Comment by mradamcox** [comment]
Arches Collector is no longer maintained, see https://community.archesproject.org/t/arches-collector-update/1580
