### ISSUE TITLE
Filter edit history for everyone but admins

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#89]
Currently, every user sees the entire edit history of the database. This must be changed so authenticated users only see the edits that they have made. Admins, however, should continue to see all of the edits across the whole database.

**Comment by mradamcox** [comment]
This should now be taken care of. @kkemp85 can you confirm?

**Comment by kkemp85** [comment]
Yes @mradamcox this is fixed! Thank you!
