### ISSUE TITLE
Standardize link behavior and colors across app

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#92]
Currently when signed in as an admin, at least one page has two different link styles:

![image](https://user-images.githubusercontent.com/10427268/72171895-7d189f80-3399-11ea-9d7d-aadc769a6447.png)

I think it's time to make a better standardization for links across the whole app (at least in the FPAN/HMS front pages, there may be places deeper in the database/arches side of things where exceptions are warranted).

Looking at the existing https://fpan.us site, here is a link
![image](https://user-images.githubusercontent.com/10427268/72172304-75a5c600-339a-11ea-83a2-1a918f0760f7.png)
and here is a link on hover
![image](https://user-images.githubusercontent.com/10427268/72172347-8c4c1d00-339a-11ea-8930-1f41eb2b5de5.png)

In our app, these should be the link styles for anonymous users, and for admin users.

For scouts, the link color should be orange (like the top bar on content sections) and on hover they should be underlined and change to the bright blue scout style color and add underline. (No font weight change.)

For state users, they should be the current dark blue (matching the state top bar on content sections), and on hover add underline and perhaps change to a lighter blue.

**Comment by mradamcox** [comment]
The "forgot password" link needs to be given the correct style.
![image](https://user-images.githubusercontent.com/10427268/72173068-5c057e00-339c-11ea-82a8-38342450ef99.png)
(this was my oversight when I added that link a little while ago.)

**Comment by coherit** [comment]
These should now all be standardized with the styles requested. The only exception is in the HMS footer -- the orange links on the aqua rice paper were a bit harsh so I made them white. [Commit 6e5901a](https://github.com/legiongis/fpan/commit/6e5901ae4802fadf7fb979d56390a2127e2d4a1e)

**Comment by mradamcox** [comment]
Ok this looks good. Thanks! It does reveal some weirdness in the resource reports: I didn't realize all of these were links!
![image](https://user-images.githubusercontent.com/10427268/72183859-a72b8b00-33b4-11ea-9178-17cd09677b1a.png)
Oh well, we'll tackle that another time. I suppose it would be nice to make them links into a search result with that value as a term, but easier said than done, I presume.
