### ISSUE TITLE
Combine Scout Profile requirements with new Scout sign up page

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#93]
Per discussion @mradamcox and I had, we would like to streamline the way scouts sign up and complete their profiles. Instead of creating an account as a two-part process where they sign up with minimal requirements (Name, email, password, ethics agreement- see first image) and then later go to their profile page to fill in detailed information (address, interests, regions with the state map, etc.- second image), we want to combine it into a single process where new scouts have to fill in the minimal requirements listed above as well as all the more detailed information listed in their scout profile at once to create a new account. No changes will be required on the scout profile page itself, they should still be able to change the current information listed there.

![image](https://user-images.githubusercontent.com/54329725/72172611-9aeb0200-33a3-11ea-9215-ae01e0553af2.png)

![image](https://user-images.githubusercontent.com/54329725/72172706-d5ed3580-33a3-11ea-98f6-c477e189ea77.png)

**Comment by mradamcox** [comment]
@kkemp85 thanks for making a ticket for this. In spirit I agree with this ticket completely, though after our conversation I was looking into it a little more and there is some procedural logic in the way we currently have it: The user account must be created before extra information can be attached to it, and we need people to verify their accounts with e-mail before we can make a new account in the database.

However, I'm sure there still are ways we can improve this whole process, so we'll keep this on the radar for sure.

**Comment by kkemp85** [comment]
Sounds good @mradamcox. The issue we have run into is that people verify their email address but never go in and complete the profile information which we need not only to track scout information for our annual reports but also to be able to assign sites to them (without choosing a region there is no way to assign a site to a scout - I'm glad this is a requirement but even direct emails to new scouts don't inspire them to go fill in this info for us).

**Comment by mradamcox** [comment]
Just want to put this here for now: Perhaps we can send an e-mail to the scout on the day after they have signed up if they haven't yet filled out this profile info. This could just be a one-time reminder. It would be a good thing to include in #37.

**Comment by mradamcox** [comment]
This has now been setup and will be deployed to staging for testing. I'm closing this ticket now, and we can open new ones for small specific changes or improvements that need to be made to the new form.

The new form is much longer:
![image](https://user-images.githubusercontent.com/10427268/130643095-35fc3937-b70f-4f0b-8bc5-d3c5414b29c4.png)
It has the same content as the old form at the top, and two more sections have been added below that.
Region choice and zip code:
![image](https://user-images.githubusercontent.com/10427268/130643291-b014e265-476a-499f-ad55-8baacdfbb390.png)
Extra background on new scout.
![image](https://user-images.githubusercontent.com/10427268/130643418-114c2732-5ad4-4b78-bef5-7be964334015.png)
